name: 'Hello World Julio Arruda'
description: 'Action de Boas Vindas'
inputs:
  who-to-greet:  # id of input
    description: 'Quem Comprimentar'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: A hora da execução'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}